# Generated by Django 5.2.6 on 2026-01-14 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('medical_concern', models.TextField()),
                ('service_type', models.CharField(choices=[('Emergency', 'Emergency'), ('Non-Emergency', 'Non-Emergency'), ('Scheduled', 'Scheduled')], max_length=20)),
                ('urgency', models.CharField(choices=[('Emergency', 'Immediate Emergency'), ('2 Hours', 'Within 2 Hours'), ('5 Hours', 'Within 5 Hours'), ('24 Hours', 'Within 24 Hours')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
