# Generated by Django 5.2.6 on 2026-01-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_doctorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorbooking',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='doctorbooking',
            name='location_source',
            field=models.CharField(choices=[('GPS', 'GPS'), ('MANUAL', 'Manual')], default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='doctorbooking',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='doctorbooking',
            name='address',
            field=models.TextField(help_text='Patient full address'),
        ),
    ]
