# Generated by Django 5.2.6 on 2026-01-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_doctorbooking_latitude_doctorbooking_location_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorbooking',
            name='location_source',
            field=models.CharField(choices=[('GPS', 'GPS'), ('MANUAL', 'Manual')], default='MANUAL', max_length=30),
        ),
    ]
