# Generated by Django 5.2.6 on 2026-01-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_doctorbooking_location_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorbooking',
            name='payment_amount',
            field=models.PositiveIntegerField(default=499),
        ),
        migrations.AddField(
            model_name='doctorbooking',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Visit'), ('QR', 'QR Payment')], default='COD', max_length=10),
        ),
        migrations.AddField(
            model_name='doctorbooking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Not Paid', 'Not Paid')], default='Pending', max_length=15),
        ),
    ]
