# Generated by Django 5.2.6 on 2026-01-17 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_doctorbooking_payment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='doctor/documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short professional introduction'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='degree_certificate',
            field=models.FileField(blank=True, null=True, upload_to='doctor/documents/degree/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_profile_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='languages',
            field=models.CharField(blank=True, help_text='Comma separated (English, Hindi, Gujarati)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='doctor/documents/pan/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor/profile_photos/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='qualification',
            field=models.CharField(blank=True, help_text='e.g. MBBS, MD', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctorprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
