# Generated by Django 5.2.6 on 2026-01-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_doctorprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short professional introduction', null=True),
        ),
    ]
